CREATE TABLE AUTHORS (
    AUTHOR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    INSTITUTION VARCHAR2(150),
    DEPARTMENT VARCHAR2(150),
    EMAIL VARCHAR2(100),
    HOMEPAGE VARCHAR2(100),
    ADDRESS VARCHAR2(200)
);
CREATE TABLE BOOKS (
    BOOK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    YEAR NUMBER(5),
    COPIES_TOTAL NUMBER DEFAULT 1,
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);
CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) UNIQUE
);
CREATE TABLE AUTHOR_BOOK (
    AUTHOR_ID NUMBER REFERENCES AUTHORS(AUTHOR_ID),
    BOOK_ID NUMBER REFERENCES BOOKS(BOOK_ID),
    PRIMARY KEY (AUTHOR_ID, BOOK_ID)
);

CREATE TABLE PUBLICATIONS (
    PUB_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    YEAR NUMBER(5),
    SOURCE VARCHAR2(200)
);

CREATE TABLE AUTHOR_PUBLICATION (
    AUTHOR_ID NUMBER REFERENCES AUTHORS(AUTHOR_ID),
    PUB_ID NUMBER REFERENCES PUBLICATIONS(PUB_ID),
    PRIMARY KEY (AUTHOR_ID, PUB_ID)
);
CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    DEPARTMENT VARCHAR2(100)
);
CREATE TABLE ADMINS (
    ADMIN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100)
);
CREATE TABLE BORROW (
    BORROW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOK_ID NUMBER REFERENCES BOOKS(BOOK_ID),
    STUDENT_ID NUMBER REFERENCES STUDENTS(STUDENT_ID),
    ADMIN_ID NUMBER REFERENCES ADMINS(ADMIN_ID),
    ISSUE_DATE DATE,
    RETURN_DATE DATE,
    RETURNED NUMBER DEFAULT 0
);
