CREATE OR REPLACE TRIGGER issue_history_log
AFTER DELETE ON ISSUED_BOOKS
FOR EACH ROW
BEGIN
    INSERT INTO ISSUE_HISTORY (BOOK_ID, STUDENT_ID, ISSUE_DATE, RETURN_DATE)
    VALUES (:OLD.BOOK_ID, :OLD.STUDENT_ID, :OLD.ISSUE_DATE, SYSDATE);

    DBMS_OUTPUT.PUT_LINE('Issue history logged for Student ID: ' || :OLD.STUDENT_ID || ' Book ID: ' || :OLD.BOOK_ID);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error logging issue history: ' || SQLERRM);
        RAISE;
END issue_history_log;
/
